version: '3.8'
services:
  app:
    build: .
    devices:
      - "/dev/dri:/dev/dri"
    network_mode: host
    command: tail -f /dev/null
    environment:
      - DISPLAY=$DISPLAY
    volumes:
      - .:/home/node/app/electron-app
      - /tmp/.X11-unix/:/tmp/.X11-unix/
    ports:
      - "3000:3001"
