export const IPC = {
  DATABASE: {
    CONNECT: 'DATABASE:CONNECT',
    DISCONNECT: 'DATABASE:DISCONNECT',
  },
  MONITOR: {
    GET_ALL_SESSIONS: 'MONITOR:GET_ALL_SESSIONS',
    FILTER_SESSION: 'MONITOR:FILTER_SESSION',
  },
}
