export const IPC = {
  DATABASE: {
    CONNECT: 'DATABASE:CONNECT',
    DISCONNECT: 'DATABASE:DISCONNECT',
  },
  MONITOR: {
    GET_ALL_SESSIONS: 'MONITOR:GET_ALL_SESSIONS',
    FILTER_SESSION: 'MONITOR:FILTER_SESSION',
    GET_COMMANDS: 'MONITOR:GET_COMMANDS',
    ERROR: 'MONITOR:ERROR',
    STOP_TRACER: 'MONITOR:STOP_TRACER',
    UPDATED: 'MONITOR:UPDATED',
    STARTED: 'MONITOR:STARTED',
    STOPPED: 'MONITOR:STOPPED',
  },
}
